### PR TITLE
create rest.Config with valid AuthProviderConfigPersister

### LINKED ISSUE #240: [Go] kubens error with Azure auth provider: invalid memory address or nil pointer dereference
When I try to use kubens it just prints an error:

```
C:\>kubens
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1115a97]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).storeTokenInCfg(0xc00023bdc0, 0xc000592000, 0xd, 0xc000592000)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:276 +0x397
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).Token(0xc00023bdc0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:206 +0x2b3
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureRoundTripper).RoundTrip(0xc0003533c0, 0xc0001e0600, 0x13e131d, 0xa, 0xc000375d80)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:125 +0x88
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc0003533e0, 0xc0001e0500, 0xc0003533e0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/transport/round_trippers.go:159 +0x1c7
net/http.send(0xc0001e0500, 0x1584520, 0xc0003533e0, 0x0, 0x0, 0x0, 0xc0000cadd8, 0x2030000, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:252 +0x445
net/http.(*Client).send(0xc00033f3e0, 0xc0001e0500, 0x0, 0x0, 0x0, 0xc0000cadd8, 0x0, 0x1, 0xc000375a20)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:176 +0x101
net/http.(*Client).do(0xc00033f3e0, 0xc0001e0500, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:699 +0x451
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:567
k8s.io/client-go/rest.(*Request).request(0xc00026e960, 0xc0000c7830, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:801 +0x3f0
k8s.io/client-go/rest.(*Request).Do(0xc00026e960, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:873 +0xdf
k8s.io/client-go/kubernetes/typed/core/v1.(*namespaces).List(0xc00036ab50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/kubernetes/typed/core/v1/namespace.go:86 +0x17e
main.queryNamespaces(0xc0000c7e68, 0xc000281408, 0x7, 0xc000281188, 0x7, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:73 +0x2b7
main.ListOp.Run(0x1584900, 0xc0000ca008, 0x1584900, 0xc0000ca010, 0x0, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:37 +0x209
main.main()
        /home/runner/work/kubectx/kubectx/cmd/kubens/main.go:20 +0x10f
```

kubectl and kubectx work.
they all are located in the same folder that is also added to the path.

using newest versions of kubectl kubectx and kubens.
OS: Windows 10 1809

### PR DESCRIPTION
**Pull request by sabbox**
Fixes #240 

Azure auth provider updates kubeconfig file when the short-lived access token (OpenID Connect) is refreshed. 
When `restclient.Config` is created via `RESTConfigFromKubeConfig` then `rest.Config.AuthConfigPersister is nil` cause we provide no information about kubeconfig file location whatsoever.

Not sure how to best handle kubeconfig file open/close properly, cause now it is opened twice.
Any ideas are welcome.

### CODE REVIEW

**Comment by ahmetb** [comment]
I think the main issue is that right now we read/parse the file ourselves to construct a YAML document tree. Then we pass the in-memory config []bytes to client-go.

But as you said, some parts of client-go would like to work on the file itself directly and when we initialize kubeconfig with in-memory []bytes it doesn't collaborate well.

I'm not sure what's the best solution... Maybe we let client-go do its thing first, then we can close-reopen-write (for modifying the pieces we need in the file). You are probably more of an expert than I am at this already, input is appreciated.

**Comment by sabbox** [comment]
> 
> I'm not sure what's the best solution... Maybe we let client-go do its thing first, then we can close-reopen-write (for modifying the pieces we need in the file). You are probably more of an expert than I am at this already, input is appreciated.

All right, let's try it this way. 
I gathered client-go interaction under two functions `namespaceExists(ns string)` and `queryNamespaces()` and I've put them before any kubens stuff. This way seqeunce open-close-reopen-write-close can be achieved.

**Comment by sabbox** [comment]
Seems that I broke a few test cases, any guidance on how to run Bats tests locally would be very helpful

**Comment by ahmetb** [comment]
https://github.com/ahmetb/kubectx/blob/51c61b862dcbf2293d5c037423356523e7df9e96/.github/workflows/ci.yml#L26-L31

**Comment by sabbox** [comment]
hi, @ahmetb any concerns regarding this one?

**Comment by sabbox** [comment]
due to PR kubernetes/kubernetes#97095
not needed anymore

**Pull request closed without merging**
