### PR TITLE
chore: upgrade Go version to 1.22

### PR DESCRIPTION
**Pull request by idsulik**
In this PR https://github.com/ahmetb/kubectx/pull/416 I added `slices.Contains`, but it's not available for Go 1.20, replaced it with custom func and added `todo`

### CODE REVIEW

**Review by ahmetb — COMMENTED** [review]
Can we upgrade Go version instead?
I suspect goreleaser file and github action and go.mod has it.

**Comment by idsulik** [comment]
@ahmetb done

**Comment by ahmetb** [comment]
The action needs to be updated too, it seems to be failing.

**Comment by idsulik** [comment]
updated it as well

**Pull request merged**
