### PR TITLE
Get namespace for validation instead of listing

### PR DESCRIPTION
**Pull request by mory91**
I opened another pull request that implements this functionality with a force option (--force/-f), This is another way that we can implement this using Namespace Get API.

### CODE REVIEW

**Comment by ahmetb** [comment]
Thanks, this is something I'm interested. Give it another gofmt.

**Comment by mory91** [comment]
Done.

**Comment by MikaelSmith** [comment]
I'm also interested, and happy to rebase and put up a new PR if needed. Right now I can't use `kubens` to switch namespace with a cluster where I have access to specific namespaces but not to list all namespaces.

**Comment by ahmetb** [comment]
@MikaelSmith nice catch. I'll close this one.

**Pull request closed without merging**
