### PR TITLE
 Add -c, --current option to get current context

### PR DESCRIPTION
**Pull request by JulienBreux**
Hi Ahmet!

To begin, thank you very much for this a-ma-zing and useful tools.

This is my tiny contribution ;)

Have a good day! 🍻

### CODE REVIEW

**Comment by JulienBreux** [comment]
I signed it!

**Comment by ahmetb** [comment]
@JulienBreux thanks for your contribution, may I ask what's your use case? When you run `kubectx` no args, we already highlight the current context.

**Comment by ahmetb** [comment]
@JulienBreux wouldn't running `kubectl config view -o=jsonpath='{.current-context}'` directly be more effective in your use case? My suspicion is that you're trying to use kubectx for scripting, as if it's a solid idempotent UNIX tool. Whereas in reality it doesn't meet those standards and is meant to be used interactively.

**Comment by JulienBreux** [comment]
@ahmetb I know, but it's very sad day to me 😂 
In fact, you'r right !
Because, it's very smart in interactive way to havs `kubectx -c` to get only the current env (not list with colors).

Be that as it may, thank you so mutch for your work @ahmetb !

**Comment by ahmetb** [comment]
Hey no problem. All I'm trying to do is to make sure we're optimizing for a prime use case and not adding features we absolutely don't need. Thanks for your idea.

**Comment by ahmetb** [comment]
I'm finally coming around to implement a feature to show current context/namespace. Please vote for it at https://github.com/ahmetb/kubectx/issues/127, I also would like to hear your opinions.

**Comment by JulienBreux** [comment]
@ahmetb ok :) Thx

**Pull request closed without merging**
