### PR TITLE
Fzf toggle pr

### PR DESCRIPTION
**Pull request by oliverisaac**
I use FZF for other things but didn't want it enabled for this tool. This PR allows EU's to selectively disable FZF for both tools or just one tool.

### CODE REVIEW

**Comment by oliverisaac** [comment]
I signed it!

**Comment by ahmetb** [comment]
ooh, this is exiciting!!!

I think we should just call it `KUBECTX_IGNORE_FZF` and use it in both kubens/kubectx (I don't see why people would disable it for one and keep it enabled for another). Can you make the change?

Also we should add to the readme something like:

> If you have `fzf` installed, but want to opt out of using this feature, set the environment variable `KUBECTX_IGNORE_FZF=1`.

**Comment by oliverisaac** [comment]
Done and done. I definitely agree with the env var name as NO_FZF felt a little to generic.

**Comment by ahmetb** [comment]
Just tested manually, looks good thanks. It'll ship in the next release.

**Pull request merged**
