### PR TITLE
Add support for Snap

### LINKED ISSUE #351: Snap support
I'm developing a Snap for kubectx+kubens and I have a functional version. I will post a PR shortly, but some points still remains:
- It needs an interface connection, which isn't automatic. The idea is to open a request to enable the auto-connection for this interface
- It requires an alias. The Snap is called "kubectx", but it has two commands: `kubectx` and `kubens`. The first one works fine, just type `kubectx` and that is it, but the second one, however, requires more effort. You need to type `kubectx.kubens`. An alias can be requested to just type `kubens`, but again, a request has to be done
- A third question is we could try to use to tracks, one for go version and another one for bash version, but more research needs to be done about that
- I couldn't make the auto-completion work on my machine, but I use Zsh, not Bash, so help will be appreciated.

### PR DESCRIPTION
**Pull request by mhalano**
Add support for Snap to Go version

Closes #351

### CODE REVIEW

**Comment by mhalano** [comment]
1. Snap is a package format with a strong confinement feature, very similar in concept to Flatpak. Snap is a Canonical's initiative. Canonical is the company behind Ubuntu. Here is a link with additional information: https://en.wikipedia.org/wiki/Snap_(software)
2. I think I can find a way to get the version in another place, I just need to know where is this place inside the source code.
3. Yes, there is. But the idea is to integrate. I could create a personal repository just with snapcraft.yaml, it would work too. But may be I could convert to a .goreleaser.yaml file. Maybe it could be better. What do you think?

**Comment by mhalano** [comment]
@ahmetb The Snap is working 100% I did some requests, and they were granted. My question is if you want I use goreleaser instead of pure snapcraft.yaml file.

**Comment by ahmetb** [comment]
We already have Goreleaser set up. So I prefer that over maintaining version number hardcoded. How does this work? Does it upload binaries etc?

**Comment by mhalano** [comment]
You generate a Snap using the command 'snapcraft' and to the upload to the Snap Store. Yes, 'snapcraft' command build your application in a clean environment (usually a VM with another tool called multipass) and generates this file .snap which you (in this case I) have to upload to the official store.

**Comment by mhalano** [comment]
@ahmetb Do I have your bless to integrate the snapcraft.yaml with the .goreleaser.yaml? If yes, I will work on that this weekend and send a new MR ASAP

**Comment by ahmetb** [comment]
Yeah go for it. Curious how it'll look like.

**Comment by mhalano** [comment]
@ahmetb I created a new commit with the Snap implementation using Goreleaser. I think it's even better because now it's possible to publish mutli-arch Snaps with a major release or a regular snapshot.

**Comment by mhalano** [comment]
Closing this PR to keep the conversation in PR #353

**Pull request closed without merging**
