### PR TITLE
split bats test invocation by binary

### PR DESCRIPTION
**Pull request by doodlesbykumbi**

### CODE REVIEW

**Comment by ahmetb** [comment]
@doodlesbykumbi why do we need this? bats is capable of running all *.bats normally.

also probably don't need the `echo` part. travis shows which cmd is being run.

**Comment by doodlesbykumbi** [comment]
@ahmetb The output for bats in one seemed to obscure where the tests are coming from or what they are for.

**Comment by ahmetb** [comment]
I agree. Feel free to take `echo`es out and I'll merge.

**Comment by doodlesbykumbi** [comment]
@ahmetb going to close this in favour of https://github.com/ahmetb/kubectx/pull/117

**Pull request closed without merging**
