### PR TITLE
Configure Dependabot

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
repo HEAD fails as above

**Comment by ahmetb** [comment]
I am good without dependabot actually, thanks. I find it unnecessarily noisy.

**Comment by gliptak** [comment]
@ahmetb would limiting PRs opened to 2(?) per type change your view?

**Comment by ahmetb** [comment]
This is an offline client side to tool that edits yaml files. I am not sure why it needs to update dependencies constantly. If anything it will destabilize a working tool more often.

**Pull request closed without merging**
