### PR TITLE
Add version flag to show kubectx and kubens version

### PR DESCRIPTION
**Pull request by gauthierc**
All programs have a version option to show which version is installed. ;-)

### CODE REVIEW

**Comment by gauthierc** [comment]
@googlebot I signed it!

**Comment by ahmetb** [comment]
Thanks for the patch but it’s better to make a proposal first. :) We are definitely not gonna read the version from source file. Goreleaser has support for version strings.

**Comment by gauthierc** [comment]
Thanks for the quick feedback. 
I didn't make a proposal for an evolution, because I found the change trivial.
I've never used Goreleaser. Indeed, it's a much better idea than putting the version number in the code.

**Comment by mathew-fleisch** [comment]
I would also like a version flag. It is hard to automate updating when you cannot verify what version you are on.

**Comment by ahmetb** [comment]
This is implemented (in Go version only), and will be in the next release. Stay tuned.

**Pull request closed without merging**
