### PR TITLE
Get current context with -c

### PR DESCRIPTION
**Pull request by seslattery**
This is a simple addition to add a -c flag to get the current context.  I've found it very useful, especially in shell prompts.

### CODE REVIEW

**Comment by seslattery** [comment]
I signed it!

**Comment by ahmetb** [comment]
`kubectx` shows the current context already in a different color. Why do you need this?

What you're looking for is `kubectl config current-context`; not a new kubectx knob.

**Comment by ahmetb** [comment]
Sorry I misunderstood. Your PR title is inaccurate: you're trying to show the current namespace.

You can also do that by running `kubens`, which shows the current namespace in a different color.

If you're trying to use "kubens -c" for scripting, do not do that and copy the logic in current_namespace function which is:

     kubectl config view -o=jsonpath="{.contexts[?(@.name==\"$(kubectl config current-context)\")].context.namespace}"

if empty, it means `default` namespace, otherwise it will return the ns of the current context.

**Comment by ahmetb** [comment]
I'm finally coming around to implement a feature to show current context/namespace. Please vote for it at https://github.com/ahmetb/kubectx/issues/127, I also would like to hear your opinions.

**Pull request closed without merging**
